### ISSUE TITLE
Question about the plug-&-play method

### ISSUE THREAD

**Issue by ariel415el** [Zhendong-Wang/Diffusion-GAN#12]
Hello and thanks for a great project and a well written paper.

I fell like there is a contradiction between what is suggested in the paper and the README of this paper.
In the paper it's said that simple noise injection was not found to be helpful in stabilizing GANs (citing results from _"Stabilizing training of generative adversarial networks through regularization"_)

However in the README a **"simple-plug-in"** method is suggested as equivalent to the full diffusionGAN method with discriminator conditioning:
**"Currently, we didn't find significant empirical differences of the two approaches"** 

Can you explain this?  
is varying noise magnitudes the reason for success? how come Roth et. al failed to make use of noise injection.
maybe it is the adaptive noise magnitude?

Thanks again.

**Comment by Zhendong-Wang** [comment]
Hi there, first thanks for your interest in our paper. I am sorry that I forgot to change the statement in the README. The timestep dependent discriminator did help improve the empirical performance in most cases, given that the discriminator could learn well on the timestep condition. The proof of Theorem2 in our paper requires the timestep dependent discriminator. 
For clarification, I provide the list below that constructs our noise injection method in the paper. 
1.	Timestep dependent discriminator
2.	Various noise magnitudes via diffusion chains. 
3.	Adaptive noise magnitude modification. 
Empirically we found timestep dependent discriminator may not necessarily improve much in some cases, but we still recommend using it since it won’t hurt the performance. We also note that how the timestep dependence is added into the discriminator is quite simple at this moment, which could be futher improved and is subject to further investigation.
